# Generated by Django 4.2 on 2023-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
