# Generated by Django 4.2 on 2023-07-08 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_marcacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='marcacion',
            name='tipo',
            field=models.CharField(default='entrada', max_length=10),
        ),
        migrations.CreateModel(
            name='Persona_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.plan')),
            ],
        ),
        migrations.AddField(
            model_name='marcacion',
            name='persona_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gym.persona_plan'),
            preserve_default=False,
        ),
    ]
