# Generated by Django 4.2 on 2023-07-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_plan_alter_marcacion_tipo_persona_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.persona')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='marcacion',
            name='persona_plan',
        ),
        migrations.DeleteModel(
            name='Persona_plan',
        ),
        migrations.AddField(
            model_name='marcacion',
            name='idPlanPersona',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.PROTECT, to='gym.planpersona'),
            preserve_default=False,
        ),
    ]
