# Generated by Django 4.2 on 2023-07-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_planpersona_remove_marcacion_persona_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcacion',
            old_name='idPlanPersona',
            new_name='plan_persona',
        ),
    ]
