# Generated by Django 4.2 on 2023-07-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_plan_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='estado',
        ),
    ]
