# Generated by Django 4.2 on 2023-09-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_persona_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='planpersona',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.estados'),
        ),
    ]
