# Generated by Django 4.2 on 2023-09-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_estados_alter_planpersona_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpersona',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
