# Generated by Django 4.2 on 2023-09-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_planpersona_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpersona',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=10),
        ),
    ]
